export enum ProtectionUnits {
  BANK_TRANSACTIONS = 'BANK_TRANSACTIONS',

  TENANT_MANAGEMENT = 'TENANT_MANAGEMENT',

  INTERNET_ACCESS_MANAGEMENT = 'INTERNET_ACCESS_MANAGEMENT',

  TOOLS_MANAGEMENT = 'TOOLS_MANAGEMENT',

  WASHING_SYSTEM_MANAGEMENT = 'WASHING_SYSTEM_MANAGEMENT',
}
